language: php

php:
    - '7.1'
    - '7.2'
    - '7.3'

install:
    - phpenv config-rm xdebug.ini || true
    - travis_retry composer install --prefer-dist -n

script:
    - php vendor/bin/php-cs-fixer fix --dry-run --diff
    - php vendor/bin/phpunit
